In [1]:
import pandas as pd

customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4, 5, 6],
    "total_spent": [350, 1200, 7500, 850, 3200, 9800]
})

customers

   customer_id  total_spent
0            1          350
1            2         1200
2            3         7500
3            4          850
4            5         3200
5            6         9800

In [2]:
def assign_segment(total_spent):
    if total_spent < 1000:
        return "Niska wartość"
    elif total_spent < 5000:
        return "Średnia wartość"
    else:
        return "Wysoka wartość"


customers["segment"] = customers["total_spent"].apply(assign_segment)

customers

   customer_id  total_spent          segment
0            1          350    Niska wartość
1            2         1200  Średnia wartość
2            3         7500   Wysoka wartość
3            4          850    Niska wartość
4            5         3200  Średnia wartość
5            6         9800   Wysoka wartość

In [3]:
segment_summary = (
    customers.groupby("segment")
    .agg(
        liczba_klientow=("customer_id", "count"),
        suma_zakupow=("total_spent", "sum")
    )
)

segment_summary

                 liczba_klientow  suma_zakupow
segment
Niska wartość                  2          1200
Wysoka wartość                 2         17300
Średnia wartość                2          4400